name: Build & Publish to Roblox

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rokit & Rojo
        run: |
          curl -sSf https://raw.githubusercontent.com/rojo-rbx/rokit/main/scripts/install.sh | bash
          echo "$HOME/.rokit/bin" >> $GITHUB_PATH
          export PATH="$HOME/.rokit/bin:$PATH"
          rokit init || true
          rokit add rojo-rbx/rojo@7.5.1
          rokit install
          rojo --version

      - name: Build place
        run: |
          mkdir -p build
          rojo build -o build/build.rbxlx

      - name: Publish place (Open Cloud)
        env:
          API_KEY: ${{ secrets.ROBLOX_API_KEY }}
          UNIVERSE_ID: ${{ vars.ROBLOX_UNIVERSE_ID }}
          PLACE_ID: ${{ vars.ROBLOX_PLACE_ID }}
        run: |
          curl -fSL \
            -H "x-api-key: $API_KEY" \
            -H "Content-Type: application/octet-stream" \
            --data-binary @build/build.rbxlx \
            "https://apis.roblox.com/universes/v1/$UNIVERSE_ID/places/$PLACE_ID/versions?versionType=Published"
